Feat/add api to project
Rater-Inc/frontend-app-v2 pull request #2
Opened 2024-12-08 15:32 UTC by Sirmelihy

types changed according to our API. And create-space endpoint implemented

2024-12-08 15:33 UTC, Sirmelihy commented on .env
considering again, that might not be good idea push to..

2024-12-15 13:28 UTC, fehmisener requested changes
Overall OK but remove the dummy comment blocks, if they're not necessary

2024-12-15 13:28 UTC, fehmisener commented on .env
Delete or change the name for local env

2024-12-15 13:28 UTC, fehmisener commented on src/components/CreateSpace/steps/SpaceBasics.tsx
> +          placeholder="Boncuky"
Change

2024-12-15 17:32 UTC, merged