Feat/melih api connect
Rater-Inc/frontend-app-v2 pull request #4
Opened 2024-12-15 22:06 UTC by Sirmelihy

These changes include:

- Implementing API to join a space.
- Redirecting space/{link} to space/{link}/select-action.
- Fixing a response bug where "example.com" was displayed; it has been corrected to "rater.me".

2024-12-15 23:53 UTC, fehmisener requested changes
Great 🧿

2024-12-15 23:53 UTC, fehmisener commented on src/App.tsx
> +
The RedirectToSelectAction component is redundant in this case. You can directly use Navigate in the Route definition:
```js
<Route 
  path="/space/:spaceId" 
  element={<Navigate to={`/space/:spaceId/select-action`} replace />} 
/>
```

2024-12-15 23:53 UTC, fehmisener commented on src/components/CreateSpace/ReviewSpace.tsx
> +                value={`https://rater.me/space/${spaceUrl}`} // TODO: Replace with actual URL
Remove the comment line as it's not needed anymore

2024-12-15 23:53 UTC, fehmisener commented on src/pages/JoinSpacePage.tsx
> +  });
Why we have this, to not load this page if token is exist and valid? We have `<ProtectedRoute>` component and already using for some of the pages. Then, we can also use it for this component.

Also `"default-space-id"` doesn't make sense actually. Without `spaceId` you can not reach this page anyway, and even if you could we shouldn't validate and send request for `default-space-id`

2025-01-07 11:17 UTC, closed without merging

2025-01-07 11:17 UTC, Sirmelihy commented
@fehmisener this PR is obsolote . Check the other one please https://github.com/Rater-Inc/frontend-app-v2/pull/6